import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/index";
import { RainbowKitWalletProvider } from "@/utils/store/rainbowKit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-landing-section bg-cover bg-no-repeat bg-dark-blue text-white ${inter.className}`}
      >
        <RainbowKitWalletProvider>
          <Navbar />
          {children}
        </RainbowKitWalletProvider>
      </body>
    </html>
  );
}
